### ISSUE TITLE
Ordem dos elementos (Assunto e Coleção) 

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-multimedia-wp-plugin#1]
No plugin multimidia (http://sms.sp.bvs.br/multimedia/) mudar a ordem dos elementos (Assunto e Coleção) na segunda coluna - deixar o item coleção como primeiro.

**Comment by viniciusandrade** [comment]
@cordeirofilho 
Vamos aproveitar esta demanda para tentar tornar a ordem dos filtros configurável pelo webmaster do site. 
O template do plugin deve respeitar a ordem escolhida pela página de ajustes do plugin.
Caso seja possível vamos aplicar o código para os demais plugins.

**Comment by cordeirofilho** [comment]
@viniciusandrade 
Criei uma opção nos ajustes para definir a ordenação da barra lateral,caso não seja definido a ordem fica: Coleção, Assuntos e Tipos de Mídia.

Veja como ficou e se está de acordo
![screenshot_2018-08-30 fi multimidia ajustes bireme wordpress](https://user-images.githubusercontent.com/460341/44877871-b3a9ba80-ac7b-11e8-9afa-9a915c02bbb9.png)

**Comment by cordeirofilho** [comment]
@viniciusandrade a biblioteca Multiselect trabalha com uma div escondida, fiz um script simples em JavaScript para resolver a classificação. 

![screenshot_2018-09-03 fi multimidia ajustes bireme wordpress](https://user-images.githubusercontent.com/460341/45000494-b8cc7980-af9b-11e8-89f0-d1ad2539be9e.png)

**Comment by viniciusandrade** [comment]
@sousajul 
Abri um chamdo no Ocomon (5844) para que o @marcoslmori possa atualizar a SMS com a opção de reordenar os filtros.
