### ISSUE TITLE
Implantar visualização de apresentações do slideshare embeded no registro multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#12]
Prezados,

Solicito incluir player do SlideShare nos registros da fonte multimedia que sejam do tipo SLIDES.

Atualmente somente aparece como uma referência:

![image](https://user-images.githubusercontent.com/13105683/49939754-d5464f00-fec4-11e8-8554-971688e07174.png)

Obrigada!
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by viniciusandrade** [comment]
@suelisuga 

Recurso implementado no plugin e atualizado no ambiente de homologação:

http://homolog.bvsalud.org/multimedia/

Esta previsto atualização do ambiente de produção para os próximos dias.
