### ISSUE TITLE
Incluir campo Coleção na busca do plug-in Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#13]
Ao buscar CRICS10 no plug-in Multimedia o resultado foi nenhum registro, no entanto há uma extensão coleção com esse nome.

Solicito incluir o campo "Coleção" na busca do plug-in Multimedia.

![image](https://user-images.githubusercontent.com/13105683/64294058-54445180-cf44-11e9-88bb-3d489c43f078.png)

![image](https://user-images.githubusercontent.com/13105683/64294017-3d056400-cf44-11e9-9c4a-0c4b083b5e7d.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga implementado em #3. Favor validar.

**Comment by marcoslmori** [comment]
atualizado o plugin da BVS BRASIL https://brasil.teste.bvs.br/multimedia
