### ISSUE TITLE
Incluir campo Autor na busca do plug-in Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#14]
Prezados,

Solicito inclusão do campo Autor na pesquisa do plug-in Multimedia.
![image](https://user-images.githubusercontent.com/13105683/64294310-d765a780-cf44-11e9-9c27-fd71cd3858d3.png)

Atualmente não é possível pesquisar, por exemplo, apresentações ou vídeos realizados por qualquer autor.

Obrigada
Sueli

Aberto em substituição a https://github.com/bireme/fi-admin/issues/895

**Comment by wilsonmoura** [comment]
@suelisuga implementado em #3. Favor validar

**Comment by marcoslmori** [comment]
atualizado o plugin da BVS BRASIL https://brasil.teste.bvs.br/multimedia
