### ISSUE TITLE
Player do Slideshare não está operacional

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#15]
Prezados,

Informo que o player do slideshare não está operando.

https://bvsalud.org/multimedia/resource/?id=multimedia.media.2688
![image](https://user-images.githubusercontent.com/13105683/64459414-3276d600-d0ce-11e9-8217-35c7d28547d3.png)

Obrigada
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga o plugin estava desatualizado no ambiente de produção.
