### ISSUE TITLE
Incluir campo Descritor Betacoronavirus na busca do plug-in Multimedia

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#18]
Prezados,

Informo que há um problema com o descritor Betacoronavirus que não está sendo recuperado na busca do Plug-in do LIS e do Multimedia.

![image](https://user-images.githubusercontent.com/13105683/75885539-73de0900-5e05-11ea-9e48-fd534a1db179.png)

![image](https://user-images.githubusercontent.com/13105683/75885577-86f0d900-5e05-11ea-95b5-d5a821d1f008.png)

Muito obrigada!
Sueli

**Comment by renatomurasaki** [comment]
@viniciusandrade informação complementar: os registros do LIS estão sendo recuperados no iAHx da BVS Regional ao buscar por mh:"betacoronavirus"

**Comment by viniciusandrade** [comment]
Correção aplicada para o índice de registros multimídia do FI-ADMIN.
