### ISSUE TITLE
Incluir player audio de podcasts

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#19]
Considerando o início do registro de áudios produzidos em canais de podcast por instituições de saúde, solicito inclusão de um player de áudio nos registrosdessa natureza.

Alguns exemplos:
SoundCloud:
CORONAVIRUS: O que fazer em caso de viagem	https://soundcloud.com/ministeriodasaude/coronavirus-o-que-fazer-em-caso-de-viagem	Ministério da Saúde
ID: 3496

CORONAVIRUS: Planos de saúde devem realizar exames para a doença	https://soundcloud.com/ministeriodasaude/coronavirus-planos-de-saude-devem-realizar-exames-para-a-doenca	
Ministério da Saúde 	
ID: 3497

CORONAVÍRUS: Ministério da Saúde não recomenda o uso do medicamento Ibuprofeno	https://soundcloud.com/ministeriodasaude/coronavirus-ministerio-da-saude-nao-recomenda-o-uso-do-medicamento-ibuprofeno	
Ministério da Saúde
ID: 3498

Coronavírus: laboratórios públicos de todo o país podem realizar exames para a doença	https://soundcloud.com/ministeriodasaude/coronavirus-laboratorios-publicos-de-todo-o-pais-podem-realizar-exames-para-a-doenca	
Ministério da Saúde
ID: 3499

Tela no soundcloud
![image](https://user-images.githubusercontent.com/13105683/77942930-c4c11000-7292-11ea-9865-06e0776b3a10.png)

Muito obrigada!
Sueli

**Comment by viniciusandrade** [comment]
@suelisuga player para o serviço soundcloud adicionado ao template de apresentação. 

Exemplo:

![soundcloud-embed](https://user-images.githubusercontent.com/349287/118170959-1712b100-b401-11eb-8aec-a0fd50341034.png)
