### ISSUE TITLE
Quantidade de registros apresentados por Coleção

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-multimedia-wp-plugin#2]
Em coleção é possível apresentar todas as coleções independente da quantidade de registros? Percebi que quando a coleção possui poucos vídeos ela não aparece na página principal, a equipe da EMS gostaria que todas aparecessem.

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/fi-admin/issues/1429

**Comment by wilsonmoura** [comment]
@sousajul ajustes realizados. Favor validar.

**Comment by sousajul** [comment]
@wilsonmoura validar onde? Essa issue é de 2015, já não lembro mais o contexto, pela descrição me parece ser no Multimidia da BVS SMS-SP, no entanto, poderia me indicar qual a instancia a ser validada? Se no teste, se na produção, onde a alteração foi realizada? Isso facilita a validação e o retorno para vcs.

@marcoslmori Solicito seu apoio nesse sentido.

No aguardo. Obrigada.
