### ISSUE TITLE
Criar cluster de Área Temática

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#24]
Solicito criar cluster de Área Temática (até 20 opções e incluir opção Ver todas)

Muito obrigada
Sueli

Relacionado https://github.com/bireme/lis-wp-plugin/issues/19

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.

**Comment by marcoslmori** [comment]
@suelisuga, Atualizado o plugin da bvs brasil https://brasil.teste.bvs.br/multimedia
