### ISSUE TITLE
Catalogo Miltimidia não aparece a caixa de pesquisa

### ISSUE THREAD

**Issue by silvalais** [bireme/fi-multimedia-wp-plugin#25]
Boa tarde!

Pessoal! o catalogo multimídia está sem caixa de pesquisa <https://bvsalud.org/multimedia>
nos 3 idiomas

![image](https://user-images.githubusercontent.com/37112458/172467431-b5531096-bda2-4310-9e15-5bd85bef67f9.png)

**Comment by viniciusandrade** [comment]
@marcoslmori quando possível poderia verificar se o plugin esta com a opção de mostrar o formulário de pesquisa marcado nas configurações?
Obrigado.

**Comment by marcoslmori** [comment]
Não estava, agora configurei
![image](https://user-images.githubusercontent.com/10047460/172626603-156087ac-29c5-4075-8012-bde2d2bc1b13.png)

**Comment by viniciusandrade** [comment]
Valeu @marcoslmori.

@silvalais favor confirmar se esta tudo OK agora. Obrigado.

**Comment by marcoslmori** [comment]
configurado
