### ISSUE TITLE
Mostrar a data de publicação no registro resumido

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#27]
Pf incluir a data de publicação no registro resumido.

![image](https://user-images.githubusercontent.com/13105683/232571467-1b9e2092-ca7f-4bbc-8317-b0fda85dae85.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga ajuste realizados. Favor validar.
