### ISSUE TITLE
Mostrar data de publicação no registro detalhado

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#28]
Pf mostrar data de publicação do recurso multimídia no registro detalhado:

![image](https://user-images.githubusercontent.com/13105683/232572614-05136b4a-0b15-43cd-9b5e-f523353936b1.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.
