### ISSUE TITLE
Criar a opção de Ordenar registros

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#29]
Pf criar a opção para o usuário poder escolher a ordem de visualização dos registros no plug-in: Data de publicação ou Data de registro.

Atualmente são apresentados pela data do registro, porém quando o CC realiza a entrada retrospectiva, documentos antigos são apresentados no início da lista, dando a impressão de que a fonte de informação está desatualizada.

Exemplo: Recurso de agosto de 2022 aparece no topo da lista.
![image](https://user-images.githubusercontent.com/13105683/232576420-b106f732-9c6d-4ad9-abf5-3291695aa050.png)

Muito obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.
