### ISSUE TITLE
Configuração da busca

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-multimedia-wp-plugin#3]
Configurar a busca para pesquisar por: título, resumo, coleção, autor, ano, programa, assunto, etc.

**Comment by suelisuga** [comment]
Issues recentes abertos e relacionados a #14 e #13.

**Comment by wilsonmoura** [comment]
@sousajul ajustes realizados. Com relação ao campo Ano, criamos um filtro/cluster para esse campo, pois por limitações técnicas não foi possível incluir esse campo na configuração da busca. Favor validar.

**Comment by sousajul** [comment]
@wilsonmoura onde que valido? onde foi feita a alteração?

**Comment by wilsonmoura** [comment]
@sousajul favor indicar ao @marcoslmori a atualização do plugin em alguma instância no ambiente de testes para que possa validar.

**Comment by sousajul** [comment]
@wilsonmoura acredito que vcs que tenham que indicar qual a instância, e a partir dai atualizar todas as instâncias que tem o plugin. Fico no aguardo para validar.

**Comment by wilsonmoura** [comment]
@sousajul o pedido de indicação de uma instância para validação é apenas para atender alguma possível preferência do usuário. Sendo assim, @marcoslmori favor encaminhar a atualização desse plugin no ambiente de testes.

**Comment by sousajul** [comment]
Validado o filtro ano no plugin.

Aproveitei para validar as issues https://github.com/bireme/fi-multimedia-wp-plugin/issues/14 e 
https://github.com/bireme/fi-multimedia-wp-plugin/issues/13. A implementação está Ok, mas a busca é realizada como campo aberto, ou seja, se busco por uma coleção com um termo X, recupera tudo que tem esse termo, inclusive outras coleções.

**Comment by wilsonmoura** [comment]
@sousajul as configurações de busca foram ajustadas conforme solicitado. Para pesquisar em algum campo específico, recomendamos utilizar o filtro do respectivo campo. Vale ressaltar que recentemente incluímos a opção "mostrar mais" em cada filtro disponível, para que o usuário possa acessar a lista completa de itens de cada filtro.

**Comment by sousajul** [comment]
Ok, Obrigada Wilson.

Att.

**Comment by suelisuga** [comment]
> Instancia atualizada https://teste.bvsalud.org/multimedia

@marcoslmori eu estava validando utilizando a instancia de teste da BVS Brasil, que por sinal está diferente da versão desse plugin do link.

A partir de agora eu olho essa instancia de teste do regional?

Aguardo para saber senão não encontro as atualizações.

Abs

**Comment by marcoslmori** [comment]
> > Instancia atualizada https://teste.bvsalud.org/multimedia

atualizado!!  

A ordem dos plugins vc pode alterar na configuração do plugin
