### ISSUE TITLE
Assunto com bug - possui &

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-multimedia-wp-plugin#4]
Em [assuntos], o link /prevenção & controle - não apresenta resultado

**Comment by suelisuga** [comment]
Prezados,

Vou fechar  o chamado porque parece-me que a pesquisa funciona se colocamos /prevenção & controle na caixa de busca:
![image](https://user-images.githubusercontent.com/13105683/82242702-b13a3900-9914-11ea-8976-a52fe115f844.png)
