### ISSUE TITLE
Criar link para filtros por canais da SMS

### ISSUE THREAD

**Issue by sousajul** [bireme/fi-multimedia-wp-plugin#5]
Seria possível criar um link por canal? A SMS tem 2 canais Canal Profissional e Canal da TV das salas de Espera das Unidades, no portal de vídeos (http://sms.sp.bvs.br/videos/) o filtro por esses dois canais é por meio de uma estratégia de busca que recupera por coleção, no entanto, a cada nova coleção que entra é necessário atualizar a estratégia de busca, se tivesse um filtro por canal seria mais fácil a manutenção e a atualização do conteúdo seria automática. 
-- Conforme solicitado, criar um tiquete para ser criado um novo campo que relacione a coleção a um agrupamento maior (conjunto)

**Comment by wilsonmoura** [comment]
@sousajul essa atividade ainda é necessária?

**Comment by wilsonmoura** [comment]
@sousajul essa atividade ainda é necessária? Depois que a BVS SMS-SP foi reformulada, o link mencionado na descrição não está mais acessível.
