### ISSUE TITLE
Ex-descritores DeCS aparecem com código de ID do antigo descritor

### ISSUE THREAD

**Issue by suelisuga** [bireme/fi-multimedia-wp-plugin#6]
Descritores DeCS frequentemente mudam de status de autorizado para sinônimos ou histórico.
O descritor "Bibliotecas Virtuais" tornou-se sinônimo de "Bibliotecas Digitais" e agora todo registro no qual foi utilizado o primeiro descritor, aparece com o número 50119.

Identifiquei esse problema sempre que há mudança no descritor e consegui identificar esse erro nos  plug-ins:

DirEve:
![image](https://user-images.githubusercontent.com/13105683/42093437-abe785e0-7b82-11e8-966c-1be7d42b408f.png)

Multimedia:
![image](https://user-images.githubusercontent.com/13105683/42093630-637519ac-7b83-11e8-9053-5004204729dd.png)

Obrigada!
Sueli

PS: Criei o mesmo chamado no plug-in DirEve: https://github.com/bireme/direve-wp-plugin/issues/9

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados no plugin DirEve. Favor validar no ambiente de testes do Portal Regional: https://teste.bvsalud.org/multimedia

**Comment by suelisuga** [comment]
@wilsonmoura na área de teste não aparece o código. então acredito que está validado.

Como faço para que possamos buscar uma forma de resolver o problema? Atualmente a solução foi não mostrar, mas inúmeros descritores seguem sem ser recuperados como em um limbo... pode me orientar sobre como encaminho a questão?

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga quando ocorre esse tipo de comportamento, significa que são IDs de termos autorizados que se tornam termos alternativos ou que são excluídos ou apagados. Sendo assim, devem ser ignorados para normalizar o cluster Assunto. No entanto, isso não resolve a origem do problema, que envolve o índice de pesquisa utilizado no plugin. Mas vale reforçar que esse ajuste foi apenas para garantir o comportamento adequado do plugin DirEve.

Existe um issue para tratar desse tema específico do índice de pesquisa: https://github.com/bireme/Gestao-DeCS/issues/58

**Comment by wilsonmoura** [comment]
@suelisuga quando ocorre esse tipo de comportamento, significa que são IDs de termos autorizados que se tornam termos alternativos ou que são excluídos ou apagados. Sendo assim, devem ser ignorados para normalizar o cluster Assunto. No entanto, isso não resolve a origem do problema, que envolve o índice de pesquisa utilizado no plugin. Mas vale reforçar que esse ajuste foi apenas para garantir o comportamento adequado do plugin Multimedia.

Existe um issue para tratar desse tema específico do índice de pesquisa: https://github.com/bireme/Gestao-DeCS/issues/58

**Comment by suelisuga** [comment]
ok @wilsonmoura ! Obrigada pelo esclarecimento. 

Uma dúvida que fiquei agora é se nos próximos anos, quando outros descritores forem apagados ou atualizados, voltaremos a ter esse problema ou se a solução de não mostrar os códigos numéricos resolve também as próximas atualizações do DeCS/MeSH.

**Comment by wilsonmoura** [comment]
@suelisuga isso vai resolver também as possíveis ocorrências nas próximas atualizações do DeCS/MeSH.

**Comment by suelisuga** [comment]
ah! que bom @wilsonmoura ! obrigada
