### ISSUE TITLE
Plugin multimedia não funciona com o enlace permanente "nombre de la entrada"

### ISSUE THREAD

**Issue by marcoslmori** [bireme/fi-multimedia-wp-plugin#8]
Somente funcionou como dia e nombre.  

Por favor, ajustar para que funcione com a configuração "Nombre de la entrada"

Caso: mtci.bvsalud,org

**Comment by viniciusandrade** [comment]
@marcoslmori 

Ajustes realizados no plugin. Favor atualizar o código na instância e realizar novo teste para validação.

**Comment by marcoslmori** [comment]
Feito, funcionando corretamente:   http://mtci.bvsalud.org/multimedia
